
GET http://localhost:4001/api/blogs


###
POST http://localhost:4001/api/blogs
Content-Type: application/json

{
   "title": "custom Validator",
  "author": "mongoose",
  "url": "https://mongoosejs.com/docs/validation.html#custom-validators",
  "likes": 200
}