
GET http://localhost:4001/api/blogs


###
POST http://localhost:4001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVtZXNoXyIsImlkIjoiNjUwMzBkMmY0ZDUyZDFhZGY3MGNjMzg5IiwiaWF0IjoxNjk1MTQzNTk2fQ.N6A-TdsIrGZgNUxRoJe8hiIj25W0saTkfPi6QQN5xiw

{
 "title": "Understanding is Important",
  "author": "mongoosesFDSFe",
  "url": "https:",
  "likes": 200,
}

###
DELETE http://localhost:4001/api/blogs/6504428f0bdbbca56c995cea
Content-Type:application/json
Authorization: Bearer 